
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: 5

development:
  <<: *default
  database: achieve123_development

test:
  <<: *default
  database: achieve123_test

production:
  url: <%= ENV['DATABASE_URL'] %>
